### ISSUE TITLE
Min samples check for image retrieval

### ISSUE THREAD

**Issue by cdbethune** [kungfuai/d3m-primitives#29]
We have some small datasets for testing that are < 1000 samples.  We're seeing a case where combination of a high `reduce_dimension` setting (1024 in this case) and a small number of samples (957) yields the error below.  It looks like you need to cap the `reduce_dimension` param to the sample size, or just disable PCA completely when the condition is violated.

```
Traceback (most recent call last):
  File "/home/zhills/Programming/d3m/d3m/runtime.py", line 1114, in _do_run_step
    self._run_step(step)
  File "/home/zhills/Programming/d3m/d3m/runtime.py", line 1104, in _run_step
    self._run_primitive(step)
  File "/home/zhills/Programming/d3m/d3m/runtime.py", line 979, in _run_primitive
    multi_call_result = self._call_primitive_method(primitive.fit_multi_produce, fit_multi_produce_arguments)
  File "/home/zhills/Programming/d3m/d3m/runtime.py", line 1080, in _call_primitive_method
    raise error
  File "/home/zhills/Programming/d3m/d3m/runtime.py", line 1076, in _call_primitive_method
    result = method(**arguments)
  File "/home/zhills/Programming/d3m/d3m/primitive_interfaces/base.py", line 534, in fit_multi_produce
    return self._fit_multi_produce(produce_methods=produce_methods, timeout=timeout, iterations=iterations, inputs=inputs, outputs=outputs)
  File "/home/zhills/Programming/d3m/d3m/primitive_interfaces/base.py", line 550, in _fit_multi_produce
    self.set_training_data(**arguments)
  File "/home/zhills/Programming/d3m-primitives/kf_d3m_primitives/remote_sensing/image_retrieval/image_retrieval.py", line 165, in set_training_data
    self.features = self._postprocess(input_features)
  File "/home/zhills/Programming/d3m-primitives/kf_d3m_primitives/remote_sensing/image_retrieval/image_retrieval.py", line 253, in _postprocess
    features = self._reduce(features)
  File "/home/zhills/Programming/d3m-primitives/kf_d3m_primitives/remote_sensing/image_retrieval/image_retrieval.py", line 276, in _reduce
    return reduce_method.fit_transform(features)
  File "/home/zhills/Programming/distil-auto-ml/ml_env/lib/python3.6/site-packages/sklearn/decomposition/_pca.py", line 369, in fit_transform
    U, S, V = self._fit(X)
  File "/home/zhills/Programming/distil-auto-ml/ml_env/lib/python3.6/site-packages/sklearn/decomposition/_pca.py", line 416, in _fit
    return self._fit_full(X, n_components)
  File "/home/zhills/Programming/distil-auto-ml/ml_env/lib/python3.6/site-packages/sklearn/decomposition/_pca.py", line 435, in _fit_full
    % (n_components, min(n_samples, n_features)))
ValueError: n_components=1024 must be between 0 and min(n_samples, n_features)=957 with svd_solver='full'
```

**Comment by jlgleason** [comment]
Addressed here: https://github.com/kungfuai/d3m-primitives/commit/21aa259556ba03f712af9af3c8a2f6ab4420f4dd.
